# Generated by Django 5.2.2 on 2025-06-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='price',
            new_name='cost',
        ),
    ]
