# Generated by Django 5.2.2 on 2025-06-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_price_carlist_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carlist',
            name='car_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Car_Brands', to='projectapp.brand'),
        ),
    ]
