# Generated by Django 5.2.2 on 2025-06-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_remove_carlist_car_company_delete_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='carlist_name',
            new_name='car_name',
        ),
    ]
