# Generated by Django 5.2.2 on 2025-06-22 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_rename_carlist_name_carlist_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='model_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
