# Generated by Django 5.2.2 on 2025-06-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_carlist_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='model_id',
        ),
    ]
