# Generated by Django 5.2.2 on 2025-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_remove_carlist_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
