# Generated by Django 5.2.2 on 2025-06-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_carlist_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='model_id',
            new_name='modelid',
        ),
    ]
