# Generated by Django 5.2.2 on 2025-06-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_rename_model_id_carlist_modelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='modelid',
            new_name='model',
        ),
    ]
