# Generated by Django 5.2.2 on 2025-06-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_rename_modelid_carlist_model'),
    ]

    operations = [
    ]
