# Generated by Django 5.2.2 on 2025-06-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_remove_model_id'),
    ]

    operations = [

    ]
