# Generated by Django 5.2.2 on 2025-06-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_remove_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='model',
            new_name='model_id',
        ),
    ]
