# Generated by Django 5.2.2 on 2025-06-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_rename_model_carlist_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='time',
        ),
    ]
