# Generated by Django 5.2.2 on 2025-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_remove_carlist_car_name_remove_carlist_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='car_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='carlist',
            name='cost',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='carlist',
            name='engine',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='carlist',
            name='model_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='carlist',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
